services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    environment:
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      #- /path/data:/var/lib/registry
      #- /path/certs:/certs
      - ./auth:/auth

      #docker run \
      #--entrypoint htpasswd \
      #httpd:2 -Bbn testuser testpassword > auth/htpasswd
      #docker compose up -d